language: generic
sudo: required

services:
  - docker

env:
  COMPOSE_VERSION: 1.23.2

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose

  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose pull

before_script:
  - bash .dev-setup

script:
  - docker-compose run --rm web rspec

addons:
  code_climate:
    repo_token: 'ff44355d041f6826c54189f18c7dac2a99c82e8efcf45d5650a29fd6f965feb5'

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms: ilabsea:C4mpJ4flOxHey8sO8SgEkg77
