language: ruby
cache: bundler

services:
  - redis-server
  - elasticsearch

addons:
  code_climate:
    repo_token: 'ff44355d041f6826c54189f18c7dac2a99c82e8efcf45d5650a29fd6f965feb5'
rvm:
  - "2.4.1"

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec

before_script:
  - sleep 10 # delay for Elasticsearch as it might take few seconds to start
  
  - cp config/application.travis.yml config/application.yml
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database cdc_call_test'

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms: ilabsea:C4mpJ4flOxHey8sO8SgEkg77
