default: &default
  TIME_ZONE: 'Bangkok'
  APP_NAME: "Zero Reporting"
  LOCAL_TZ: "Asia/Phnom_Penh"

  # sync report progress status to fetch 50 for every internal 2 minute
  # ENV doesn't support integer
  SYNC_FETCH_SIZE: '50'

  # Verboice
  VERBOICE_URL: 'http://localhost/api2'

  VERBOICE_NOTIFY_STATUS_USER: 'test'
  VERBOICE_NOTIFY_STATUS_PWD: '123456'
  HOST: 'http://localhost:3000'

  CDC_DATABASE_PASSWORD: ""
  SECRET_KEY_BASE: ""

  # code climate
  CODECLIMATE_REPO_TOKEN: ""

  # Nuntium
  NUNTIUM_HOST: 'http://nuntium.instedd.org'
  NUNTIUM_ACCOUNT: ''
  NUNTIUM_APP: ''
  NUNTIUM_APP_PWD: ''

  # sidekiq
  SIDEKIQ_USERNAME: ''
  SIDEKIQ_PASSWORD: ''
  DELAY_DELIVER_IN_MINUTES: '1'

  HUB_QUEUE_NAME: 'hub'
  DEFAULT_QUEUE_NAME: 'default'

  # Alert threshold
  THRESHOLD_FORMULA: "(W<sub>n-1</sub>+W<sub>n-2</sub>+W<sub>n-3</sub>)/3 * 1.5"
  THRESHOLD_WEEK_RANGE: '3'

  EXTERNAL_MESSAGE_TEMPLATE: "{{caller_phone}} has left voice message on call log {{call_log_id}}"
  REPORTED_CASE_ALERT_TEMPLATE: "{{name}}: {{value}}({{exceed_value}})"

  # API credential
  API_DEFAULT_VERSION: 'v1'
  API_USERNAME: 'test'
  API_CREDENTIAL: 'test'

  # HUB: '1' => enabled, '0' => disabled
  HUB_ENABLED: '1'

  # LOGO
  LOGO_URL: 'path_to_image'

  # Backup
  BACKUP_SCRIPT_PATH: ''
  BACKUP_MODEL_NAME: ''
  BACKUP_NOTIFY_EMAIL: ''
  CONFIG_PATH_TO_BACKUP: ''
  ASSET_PATH_TO_BACKUP: ''

  # Setting
  NUM_OF_REVISE_WEEK: '3'

  EXCEPTIONAL_YEAR: '2012,2016'
  WKST: '3' # sunday:0, monday:1, ...

  # Elasticsearch '1' => enabled, '0' => disabled
  ELASTICSEARCH_ENABLED: '0'

  # use comma separator
  BLACKLIST_NUMBERS: ''

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
