default: &default
  TIME_ZONE: 'Bangkok'
  APP_NAME: "CDC Zero Reporting System"
  LOCAL_TZ: "Asia/Phnom_Penh"

  # Verboice
  VERBOICE_URL: 'http://localhost/api2'

  VERBOICE_NOTIFY_STATUS_USER: 'test'
  VERBOICE_NOTIFY_STATUS_PWD: '123456'
  HOST: 'http://localhost:3000'

  # code climate
  CODECLIMATE_REPO_TOKEN: "b2207aa683bedabf3e9cddc692141d0df7ce871f54f8ca8bc2774c7fd4e2bb8a"
  CDC_DATABASE_PASSWORD: ""
  SECRET_KEY_BASE: "15ed7d3c83435080ee807c78f2f50a726ba41532186d420db4c66b23fbe3741ffc130f1a792dec0a9a6e7a5be006164bb945f66c1a8a8ce7a4404ac1f8c1b94d"

  # Nuntium
  NUNTIUM_HOST: 'http://nuntium.instedd.org'
  NUNTIUM_ACCOUNT: ''
  NUNTIUM_APP: ''
  NUNTIUM_APP_PWD: ''

  # sidekiq
  SIDEKIQ_USERNAME: ''
  SIDEKIQ_PASSWORD: ''
  DELAY_DELIVER_IN_MINUTES: '1'

  # Alert threshold
  THRESHOLD_FORMULA: "(W<sub>n-1</sub>+W<sub>n-2</sub>+W<sub>n-3</sub>)/3 * 1.5"
  THRESHOLD_WEEK_RANGE: '3'

  EXTERNAL_MESSAGE_TEMPLATE: "{{caller_phone}} has left voice message on call log {{call_log_id}}"
  REPORTED_CASE_ALERT_TEMPLATE: "{{name}}: {{value}}({{exceed_value}})"

  # API credential
  API_DEFAULT_VERSION: 'v1'
  API_USERNAME: 'test'
  API_CREDENTIAL: 'test'

  # HUB: '1' => enabled, '0' => disabled
  HUB_ENABLED: '1'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
