default: &default
  TIME_ZONE: 'Bangkok'
  APP_NAME: "Zero Reporting"
  LOCAL_TZ: "Asia/Phnom_Penh"

  # Verboice
  VERBOICE_URL: 'http://localhost/api2'

  VERBOICE_NOTIFY_STATUS_USER: 'test'
  VERBOICE_NOTIFY_STATUS_PWD: '123456'
  HOST: 'http://localhost:3000'

  # code climate
  CODECLIMATE_REPO_TOKEN: "ff44355d041f6826c54189f18c7dac2a99c82e8efcf45d5650a29fd6f965feb5"
  CDC_DATABASE_PASSWORD: ""
  SECRET_KEY_BASE: "15ed7d3c83435080ee807c78f2f50a726ba41532186d420db4c66b23fbe3741ffc130f1a792dec0a9a6e7a5be006164bb945f66c1a8a8ce7a4404ac1f8c1b94d"

  # Nuntium
  NUNTIUM_HOST: 'http://nuntium.instedd.org'
  NUNTIUM_ACCOUNT: ''
  NUNTIUM_APP: ''
  NUNTIUM_APP_PWD: ''

  # sidekiq
  SIDEKIQ_USERNAME: ''
  SIDEKIQ_PASSWORD: ''
  DELAY_DELIVER_IN_MINUTES: '1'

  # Alert threshold
  THRESHOLD_FORMULA: "(W<sub>n-1</sub>+W<sub>n-2</sub>+W<sub>n-3</sub>)/3 * 1.5"
  THRESHOLD_WEEK_RANGE: '3'

  EXTERNAL_MESSAGE_TEMPLATE: "{{caller_phone}} has left voice message on call log {{call_log_id}}"
  REPORTED_CASE_ALERT_TEMPLATE: "{{name}}: {{value}}({{exceed_value}})"

  # API credential
  API_DEFAULT_VERSION: 'v1'
  API_USERNAME: 'test'
  API_CREDENTIAL: 'test'

  # HUB: '1' => enabled, '0' => disabled
  HUB_ENABLED: '1'

  # Backup
  BACKUP_SCRIPT_PATH: ''
  BACKUP_MODEL_NAME: ''
  BACKUP_NOTIFY_EMAIL: ''
  CONFIG_PATH_TO_BACKUP: ''
  ASSET_PATH_TO_BACKUP: ''

  # Setting
  NUM_OF_REVISE_WEEK: '3'

  EXCEPTIONAL_YEAR: '2012,2016'
  WKST: '3' # sunday:0, monday:1, ...

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
